version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: djcookie_demo_proj_local_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: djcookie_demo_proj_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: djcookie_demo_proj_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./djcookie_demo_proj:/app/djcookie_demo_proj:z
    ports:
      - "7000:7000"
    command: /start-docs

  react:
    build:
      context: .
      dockerfile: ./compose/local/frontend/Dockerfile
      target: development
    image: djcookie_demo_proj_local_frontend_react
    container_name: react_frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    env_file:
      - ./.envs/.local/.frontend
    ports:
      - 3000:3000